### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.DOMAIN_ADAPTATION_ON' caused by cfg.merge_from_file

### ISSUE THREAD

**Issue by WanyiLi** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#4]
Hi, when i run the script to test trained model, KeyError occurs.
the used script: python tools/test_net.py --config_file "configs/da_faster_rcnn/e2e_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml" MODEL.WEIGHT trainedmodels/model_final.pth
detailed error: 
Traceback (most recent call last):
  File "tools/test_net.py", line 98, in <module>
    main()
  File "tools/test_net.py", line 50, in main
    cfg.merge_from_file(args.config_file)
  File "/home/casia_robot_lwy/anaconda3/envs/py3_env/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/casia_robot_lwy/anaconda3/envs/py3_env/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/casia_robot_lwy/anaconda3/envs/py3_env/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/casia_robot_lwy/anaconda3/envs/py3_env/lib/python3.7/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.DOMAIN_ADAPTATION_ON'

**Comment by krumo** [comment]
@WanyiLi Hi, did you solve this problem? As I mentioned in the installation instruction, you have to follow the [instructions](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md) in maskrcnn_benchmark to install this repo. Specifically, you have to download this repo and compile **this repo** locally so that your environment could find the key 'MODEL.DOMAIN_ADAPTATION_ON' defined in the config file.

**Comment by WanyiLi** [comment]
@krumo Thank you. This problem is solved by copy maskrcnn_benchmark files of this repo to installation dir of maskrcnn-benchmark library. Any other undefined key can also be defined in the installed config definition file, i.e. maskrcnn-benchmark/maskrcnn_benchmark/config/defaults.py.
Thanks again!
