### ISSUE TITLE
ImportError: No module named 'torchvision'

### ISSUE THREAD

**Issue by wzr0108** [krumo/Domain-Adaptive-Faster-RCNN-PyTorch#47]
my env is 
torch 1.4.0
torchvision 0.5.0
cuda 10.1
```
Traceback (most recent call last):
  File "D:/Domain-Adaptive-Faster-RCNN-PyTorch/train_net.py", line 18, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\engine\inference.py", line 10, in <module>
    from maskrcnn_benchmark.data.datasets.evaluation import evaluate
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\data\datasets\evaluation\__init__.py", line 3, in <module>
    from .coco import coco_evaluation
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\data\datasets\evaluation\coco\__init__.py", line 1, in <module>
    from .coco_eval import do_coco_evaluation
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\data\datasets\evaluation\coco\coco_eval.py", line 10, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\structures\boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\layers\__init__.py", line 8, in <module>
    from .nms import nms
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\layers\nms.py", line 4, in <module>
    from ._utils import _C
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\layers\_utils.py", line 39, in <module>
    _C = _load_C_extensions()
  File "D:\Domain-Adaptive-Faster-RCNN-PyTorch\maskrcnn_benchmark\layers\_utils.py", line 35, in _load_C_extensions
    extra_include_paths=extra_include_paths,
  File "C:\Users\wzr\Miniconda3\envs\da\lib\site-packages\torch\utils\cpp_extension.py", line 684, in load
    is_python_module)
  File "C:\Users\wzr\Miniconda3\envs\da\lib\site-packages\torch\utils\cpp_extension.py", line 881, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\wzr\Miniconda3\envs\da\lib\site-packages\torch\utils\cpp_extension.py", line 1089, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\wzr\Miniconda3\envs\da\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'torchvision'
```

**Comment by puliang292** [comment]
您好，遇到了同样的问题，您这个问题解决了吗？

**Comment by wzr0108** [comment]
没解决，放弃了

**Comment by zhengying455** [comment]
> 
您解决了吗？

**Comment by zhengying455** [comment]
> 您好，遇到了同样的问题，您这个问题解决了吗？

您解决了吗？

**Comment by wzr0108** [comment]
没解决，放弃了

**Comment by zhengying455** [comment]
> 没解决，放弃了

您有跑通的UDA的code可以分享一下吗，救

**Comment by wzr0108** [comment]
后面去做uda分割了，检测没做了
